### PR TITLE
[5] Fix for IAP Auth Issues

### PR DESCRIPTION
**Pull request by ryanm101**
Fix for https://github.com/adohkan/git-remote-https-iap/issues/5

### CODE REVIEW

**Comment by ryanm101** [comment]
@solsson  Do you want to try this and see if it solves your issue?

**Comment by solsson** [comment]
Confirmed! Well done 👏 

It's interesting that the success rate with `GCP_IAAP_AUTH_TOKEN` seemed to degrade day by day. Today it was really terrible. Is GCP in the midst of a gradual rollout that de-supports cookie auth? Did you get an answer to your ticket?

**Comment by ryanm101** [comment]
Apparently they will look into it and update me by the 24th of Jan..

**Comment by solsson** [comment]
> Apparently they will look into it and update me by the 24th of Jan..

I think this PR is an improvement anyway, but it's interesting to know if there are changes to IAP in general. There's no hints of that in https://cloud.google.com/iap/docs/release-notes.

**Comment by ryanm101** [comment]
| There's no hints of that in https://cloud.google.com/iap/docs/release-notes.

Yes I KNOW!!!! 

It was very annoying trying to figure out where the problem lay as we'd recently made some infra changes on our side. You're reporting of the issue here helped us confirm it wasn't something we'd done, so thank you for that.

**Pull request merged**
